apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: wddl
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: wddl
    app.kubernetes.io/part-of: byoc-app-yvsx
  name: wddl
spec:
  ports:
  - name: "8081"
    port: 8081
    targetPort: 8081
  selector:
    app.kubernetes.io/instance: wddl
status:
  loadBalancer: {}
